//LOCALHOST
### Get all users
GET http://localhost:3000/users

### Get users by id
GET  http://localhost:3000/users/6504a8506e172695cf2b8d9d

### create user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Nathan",
    "lastName":"Adeleye",
    "email": "nat@test.com",
    "favoriteColor":"green",
    "birthdate":"2/9/2014"
}

### Put user
PUT http://localhost:3000/users/6504a8506e172695cf2b8d9d HTTP/1.1
Content-Type: application/json

{
    "firstName": "Samuel",
    "lastName": "Kofi",
    "email": "test@example.com",
    "favoriteColor":"black",
    "birthdate": "6/7/1987"
}

### Delete user
DELETE http://localhost:3000/users/6504a7ae6e172695cf2b8d9b HTTP/1.1
